// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhskuqmwuvpcgqljcdct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoc2t1cW13dXZwY2dxbGpjZGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMjYwOTcsImV4cCI6MjA3NjkwMjA5N30.lxHYJEkRALwdL71Pt6l-f5yDyMudJjJQPvKYM5z0Vdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});